"""
CrossFit Dashboard UI

Visualizes CrossFit-specific training metrics.
"""

from __future__ import annotations

import streamlit as st


def render_crossfit_dashboard(
    history_summary: dict,
) -> None:
    """
    Render the CrossFit dashboard section.

    Parameters
    ----------
    history_summary
        Summary generated by history.build_history_summary().
    """

    coverage = history_summary.get(
        "crossfit_coverage",
        {},
    )

    movements = history_summary.get(
        "crossfit_movements",
        {},
    )

    missing = history_summary.get(
        "missing_crossfit_movements",
        [],
    )

    st.header("🏋️ CrossFit Skills")

    # ------------------------------------------------------------------
    # Coverage
    # ------------------------------------------------------------------

    c1, c2, c3 = st.columns(3)

    with c1:

        st.metric(
            "Coverage",
            f"{coverage.get('coverage_percent', 0):.1f} %",
        )

    with c2:

        st.metric(
            "Movement Families",
            coverage.get("covered", 0),
        )

    with c3:

        st.metric(
            "Expected",
            coverage.get("expected", 0),
        )

    st.divider()

    # ------------------------------------------------------------------
    # Trained movements
    # ------------------------------------------------------------------

    st.subheader("✅ Trainierte Movement Families")

    if movements:

        sorted_movements = sorted(
            movements.items(),
            key=lambda x: x[1],
            reverse=True,
        )

        for movement, count in sorted_movements:

            st.progress(
                min(count / 20, 1.0),
                text=f"{movement.replace('_',' ').title()} ({count})",
            )

    else:

        st.info(
            "Noch keine CrossFit-Movements erkannt."
        )

    st.divider()

    # ------------------------------------------------------------------
    # Missing movements
    # ------------------------------------------------------------------

    st.subheader("🎯 Noch nicht trainiert")

    if missing:

        for movement in missing:

            st.checkbox(
                movement.replace("_", " ").title(),
                value=False,
                disabled=True,
            )

    else:

        st.success(
            "Alle erwarteten Movements wurden trainiert."
        )